title: Loja de Quadrinhos
email: josetelesmaciel@gmail.com
description: >-
  Loja de Quadrinhos é uma listagem com mais de 10 mil quadrinhos do mercado nacional brasileiro.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  lojadequadrinhos
permalink: /:title

# Build settings
theme: minima
paginate: 30
paginate_path: "/pagina:num/"
plugins:
  - jekyll-feed
collections:
  comics:
    output: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
